#!/bin/bash

export AGENT_INFRA_DIR=`cd \`dirname $( readlink -f $BASH_SOURCE ) \` && pwd`
export PATH=$AGENT_INFRA_DIR/bin:$PATH

export AGENT_INFRA_MODELS_DIR=$AGENT_INFRA_DIR/models

#export AGENT_INFRA_MODEL="Qwen/Qwen2.5-Coder-1.5B-Instruct"
#export AGENT_INFRA_MODEL_TOOL_CALL_PARSER="hermes"
#export AGENT_INFRA_MODEL_REASONING_PARSER="auto"
#export AGENT_INFRA_MODEL_TOKENIZER=""


export AGENT_INFRA_MODEL="QuantTrio/Qwen3.5-4B-AWQ" 
export AGENT_INFRA_MODEL_TOOL_CALL_PARSER="qwen3_coder"
export AGENT_INFRA_MODEL_REASONING_PARSER="qwen3"


export AGENT_INFRA_DEV_TOOLS=$AGENT_INFRA_DIR/dev-tools

export AGENT_INFRA_LOG_DIR=$AGENT_INFRA_DIR/logs

export AGENT_INFRA_DATA_DIR=$AGENT_INFRA_DIR/data


alias dport='docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a'

#After installing and running the services ( install directory and services directory ),  
#Get API KEY from the NewAPI admin web intraface (http://localhost:3000/keys) , click on the copy icon near the Api Key of API_KEY_0 line.
#The api key below is the one i get from my local machine.
export OPENAI_API_KEY="sk-EoJCdSt5ZfEzQqny7AlzEfeyNiwRpT96bgrWnwKWGCSNPOgQ"
# Adress of the local newapi gateway
export OPENAI_BASE_URL="http://localhost:3000/v1"  
# The name "/local_model" is set in newapi
export OPENAI_MODEL=/local_model


echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ">>> AGENT_INFRA_DIR=$AGENT_INFRA_DIR "
echo ">>> AGENT_INFRA_MODEL=$AGENT_INFRA_MODEL "
echo ">>> AGENT_INFRA_DEV_TOOLS=$AGENT_INFRA_DEV_TOOLS "
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
if [ -f ~/sdk/rust-dev-env/release ]
then
. ~/sdk/rust-dev-env/release
fi


