#!/bin/bash

export AGENT_INFRA_DIR=`cd \`dirname $( readlink -f $BASH_SOURCE ) \` && pwd`
export PATH=$AGENT_INFRA_DIR/bin:$PATH

export AGENT_INFRA_MODELS_DIR=$AGENT_INFRA_DIR/models

#export AGENT_INFRA_MODEL="Qwen/Qwen2.5-Coder-1.5B-Instruct"
#export AGENT_INFRA_MODEL_TOOL_CALL_PARSER="hermes"
#export AGENT_INFRA_MODEL_REASONING_PARSER="auto"
#export AGENT_INFRA_MODEL_TOKENIZER=""


export AGENT_INFRA_MODEL="QuantTrio/Qwen3.5-4B-AWQ" 
export AGENT_INFRA_MODEL_TOOL_CALL_PARSER="qwen3_coder"
export AGENT_INFRA_MODEL_REASONING_PARSER="qwen3"


export AGENT_INFRA_DEV_TOOLS=$AGENT_INFRA_DIR/dev-tools

export AGENT_INFRA_LOG_DIR=$AGENT_INFRA_DIR/logs

export AGENT_INFRA_DATA_DIR=$AGENT_INFRA_DIR/data


alias dport='docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a'


#export KILO_PROVIDER="openai-compatible"
#export KILO_BASE_URL="http://localhost:3000/v1"
#export OPENAI_BASE_URL="http://localhost:3000/v1"
#export OPENAI_API_BASE="http://localhost:3000/v1"
#export KILO_MODEL="openai-compatible/local_model"
##export KILO_MODEL="Qwen/Qwen2.5-Coder-1.5B-Instruct"
#export KILO_API_KEY="sk-EoJCdSt5ZfEzQqny7AlzEfeyNiwRpT96bgrWnwKWGCSNPOgQ"


if [ -f ~/sdk/rust-dev-env/release ]
then
. ~/sdk/rust-dev-env/release
fi


